Clinic Managment/Models/Visit.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using ChartJSCore.Models;
using Humanizer.Localisation;
using System.Collections.Generic;
using System.ComponentModel;

namespace Clinic_Managment.Models
{

    public class Visit
    {
    
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public int ID { get; set; }

        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy hh:mm tt}")]
        public DateTime VistDate { get; set; }
        [Required]
        public int doctorId { get; set; }
        [Required]
        public int patientId { get; set; }
        [Required]
        public int clinicID { get; set; }
        [Display(Name = "Doctor")]
        [DataType(DataType.Text)]
        [Required (ErrorMessage = "Please enter your Doctor")]
        public virtual Doctor Doctor { get; set; }
        [Display(Name = "Patient")]
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Please enter your Patient")]
        public virtual Patient Patient { get; set; }
        [Display(Name = "Clinic")]
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Please enter your Clinic")]
        public virtual Clinic Clinic { get; set; }

    }

    }

Clinic Managment/Areas/Managment/Controllers/VisitController.cs
using Clinic_Managment.Models;
using Humanizer;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.IdentityModel.Tokens;
using Microsoft.SqlServer.Server;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net;
using System.Web.WebPages;

namespace Clinic_Managment.Areas.Managment.Controllers
{
    [Area("Managment")]
    [Authorize]
    public class VisitController : Controller
    {
        private readonly Userdata _context;
        public VisitController(Userdata context)
        {
            _context = context;
        }
      
        public IActionResult VisitIndex()
        {
            var model = new List<VisitsModels>();
            model = _context.Visits
            .Select(x => new VisitsModels
            {
                ID = x.ID,
                VistDate = x.VistDate,
                DoctorId = x.doctorId,
                PatientId = x.patientId,
                ClinicID = x.clinicID,
                DoctorName = x.Doctor.Name,
                PatientName = x.Patient.Name,
                Clinic = x.Clinic.clinic
            })
            .ToList();
            return View(model);

        }
      public JsonResult Getdoctor(string doctorname)
        {
            var doctorList = _context.Doctor.Where(x => x.Name.Contains(doctorname)).ToList();
            var doctorData = doctorList.Select(x => new
            {
                id = x.doctorId,
                text = x.Name
            });
            return Json(doctorData);
        }
        public JsonResult GetPatient(string Patientname)
        {
            var PatientList = _context.Patient.Where(x => x.Name.Contains(Patientname)).ToList();
            var PatientData = PatientList.Select(x => new
            {
                id = x.patientId,
                text = x.Name
            });
            return Json(PatientData);
        }
        public JsonResult GetClinic(string Clinictname)
        {
            var ClinicPatientList = _context.Clinic.Where(x => x.clinic.Contains(Clinictname)).ToList();
            var ClinicData = ClinicPatientList.Select(x => new
            {
                id = x.clinicID,
                text = x.clinic
            });
            return Json(ClinicData);
        }


        public JsonResult Getvisits(string vists)
        {
            var listvisit = _context.Visits
             .Where(x => x.Doctor.Name.Contains(vists.ToUpper()))
             .Select(x => new
            {
                id =  x.doctorId,
                text = x.Doctor.Name,
            }).ToList();
            return Json(listvisit);
        }

        public JsonResult Getvisitss(string vistss)
        {
            var listvisita = _context.Visits
             .Where(x => x.Patient.Name.Contains(vistss.ToUpper()))
             .Select(x => new
             {
                 id = x.patientId,
                 text = x.Patient.Name,
             }).ToList();
            return Json(listvisita);
        }


        public JsonResult Getvisitssss(string vistssss)
        {
            var listvisist = _context.Visits
             .Where(x => x.Clinic.clinic.Contains(vistssss.ToUpper()))
             .Select(x => new
             {
                 id = x.clinicID,
                 text = x.Clinic.clinic,
             }).ToList();
            return Json(listvisist);
        }
        public IActionResult visitlist(string doctors ,  string patient, string clinic ,DateTime startdate, DateTime enddate)
        {
            var model = new List<VisitsModels>();
            var SearchList = new Visit();
            if (!string.IsNullOrEmpty(doctors) && !string.IsNullOrEmpty(patient) && !string.IsNullOrEmpty(clinic))
            {
                var doctorids = doctors.Split(',').Select(Int32.Parse).ToList();
                var patientids = patient.Split(',').Select(Int32.Parse).ToList();
                var clinicids = clinic.Split(',').Select(Int32.Parse).ToList();
                model = _context.Visits.Where(x => doctorids.Contains(x.doctorId) && patientids.Contains(x.patientId) && clinicids.Contains(x.clinicID))
                    .Select(x => new VisitsModels
                    {
                        ID = x.ID,
                        VistDate = x.VistDate,
                        DoctorId = x.doctorId,
                        PatientId = x.patientId,
                        ClinicID = x.clinicID,
                        DoctorName = x.Doctor.Name,
                        PatientName = x.Patient.Name,
                        Clinic = x.Clinic.clinic
                    }).ToList();
            }

            else if (string.IsNullOrEmpty(doctors) && !string.IsNullOrEmpty(patient) && !string.IsNullOrEmpty(clinic))
            {
                var patientids = patient.Split(',').Select(Int32.Parse).ToList();
                var clinicids = clinic.Split(',').Select(Int32.Parse).ToList();
                model = _context.Visits.Where(x => patientids.Contains(x.patientId) && clinicids.Contains(x.clinicID))
                       .Select(x => new VisitsModels
                       {
                           ID = x.ID,
                           VistDate = x.VistDate,
                           DoctorId = x.doctorId,
                           PatientId = x.patientId,
                           ClinicID = x.clinicID,
                           DoctorName = x.Doctor.Name,
                           PatientName = x.Patient.Name,
                           Clinic = x.Clinic.clinic
                       }).ToList();
            }


            else if (!string.IsNullOrEmpty(doctors) && string.IsNullOrEmpty(patient) && !string.IsNullOrEmpty(clinic))
            {
                var doctorids = doctors.Split(',').Select(Int32.Parse).ToList();
                var clinicids = clinic.Split(',').Select(Int32.Parse).ToList();
                model = _context.Visits.Where(x => doctorids.Contains(x.doctorId) && clinicids.Contains(x.clinicID))
                       .Select(x => new VisitsModels
                       {
                           ID = x.ID,
                           VistDate = x.VistDate,
                           DoctorId = x.doctorId,
                           PatientId = x.patientId,
                           ClinicID = x.clinicID,
                           DoctorName = x.Doctor.Name,
                           PatientName = x.Patient.Name,
                           Clinic = x.Clinic.clinic
                       }).ToList();
            }


            else if (!string.IsNullOrEmpty(doctors) && !string.IsNullOrEmpty(patient) && string.IsNullOrEmpty(clinic))
            {
                var doctorids = doctors.Split(',').Select(Int32.Parse).ToList();
                var patientids = patient.Split(',').Select(Int32.Parse).ToList();
                model = _context.Visits.Where(x => doctorids.Contains(x.doctorId) && patientids.Contains(x.patientId))
                       .Select(x => new VisitsModels
                       {
                           ID = x.ID,
                           VistDate = x.VistDate,
                           DoctorId = x.doctorId,
                           PatientId = x.patientId,
                           ClinicID = x.clinicID,
                           DoctorName = x.Doctor.Name,
                           PatientName = x.Patient.Name,
                           Clinic = x.Clinic.clinic
                       }).ToList();
            }


            else if (string.IsNullOrEmpty(doctors) && string.IsNullOrEmpty(patient) && string.IsNullOrEmpty(clinic) && string.IsNullOrEmpty(startdate.ToString()) && string.IsNullOrEmpty(enddate.ToString()))
            {
                model = _context.Visits
                       .Select(x => new VisitsModels
                       {
                           ID = x.ID,
                           VistDate = x.VistDate,
                           DoctorId = x.doctorId,
                           PatientId = x.patientId,
                           ClinicID = x.clinicID,
                           DoctorName = x.Doctor.Name,
                           PatientName = x.Patient.Name,
                           Clinic = x.Clinic.clinic
                       }).ToList();
            }

            else if (!string.IsNullOrEmpty(doctors) && string.IsNullOrEmpty(patient) && string.IsNullOrEmpty(clinic))
            {
                var doctorids = doctors.Split(',').Select(Int32.Parse).ToList();
                model = _context.Visits.Where(x => doctorids.Contains(x.doctorId))
                       .Select(x => new VisitsModels
                       {
                           ID = x.ID,
                           VistDate = x.VistDate,
                           DoctorId = x.doctorId,
                           PatientId = x.patientId,
                           ClinicID = x.clinicID,
                           DoctorName = x.Doctor.Name,
                           PatientName = x.Patient.Name,
                           Clinic = x.Clinic.clinic
                       }).ToList();
            }

            else if (string.IsNullOrEmpty(doctors) && !string.IsNullOrEmpty(patient) && string.IsNullOrEmpty(clinic))
            {
                var patientids = patient.Split(',').Select(Int32.Parse).ToList();
                model = _context.Visits.Where(x => patientids.Contains(x.patientId))
                       .Select(x => new VisitsModels
                       {
                           ID = x.ID,
                           VistDate = x.VistDate,
                           DoctorId = x.doctorId,
                           PatientId = x.patientId,

Clinic Managment/Areas/Managment/Views/Visit/AddVisits.cshtml
@model Clinic_Managment.VisitEditor
@{
    Layout = null;
}
<input type="text" id="doctorName" value="@Model.doctorName" style="display:none;" />
<input type="text" id="patientName" value="@Model.patientName" style="display:none;" />
<input type="text" id="ClinicName" value="@Model.ClinicName" style="display:none;" />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        <div class="form-group">
            <label class="col-md-3">
                Doctor
            </label>
            <div class="col-md-9">
                <span id="msgdoctor1" class="text-danger" style="display:none">Please, the Doctor value is not filled</span>
                <select id="doctorId" style="width:350px;">
                    @Html.ValidationMessageFor(x => x.doctorId, Model.doctorName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.doctorName, "", new { @class = "text-danger" })
                </select>

            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3">
                Patient
            </label>
            <div class="col-md-9">
                <span id="msgpatient1" class="text-danger" style="display:none">Please, the Patient value is not filled</span>
                <select id="patientId" style="width:350px;">
                    @Html.ValidationMessageFor(x => x.patientId, Model.patientName, new { @class = "form-control" })
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3">
                Clinic
            </label>
            <div class="col-md-9">
                <span id="msgClinic1" class="text-danger" style="display:none">Please, the Clinic value is not filled</span>
                <select id="clinicID" style="width:350px;">
                    @Html.ValidationMessageFor(x => x.clinicID, Model.ClinicName, new { @class = "form-control" })
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3">
                VistDate
            </label>
            <div class="col-md-9">
                <span id="msgVistDate2" class="text-danger" style="display:none">The date is not real, please be greater than the date</span>
                <span id="msgVistDate1" class="text-danger" style="display:none">Please, the VistDate value is not filled</span>
                <span id="msgVistDate" class="text-danger" style="display:none">Please, the Date is in the database, choose another Date</span>
                <input  class="form-control" asp-for="VistDate" asp-format="{0:yyyy-MM-ddTHH:mm}"/>
            </div>
        </div>

        <br /><br /><br />
        <center>
            <div class="form-group">
                <div class="col-md-12">
                    <button type="button" onclick="AddVisits()" class="btn btn-outline-primary" id="add_variation">Save</button>
                </div>
            </div>
        </center>
    </div>
}

<script type="text/javascript">
    debugger;
    var doctorname = $("#doctorName").val();
    var datadoctor = $("<option/>", { value: @Model.doctorId, text: doctorname });
    $('#doctorId').append(datadoctor);
    $('#doctorId option[value="' + @Model.doctorId, + '"]').prop('selected', true);
    $('#doctorId').trigger('change');

    $(document).ready(function () {
        $("#doctorId").select2({

            dropdownParent: $('#form-modalsss'),
            ajax: {
                url: '@Url.Action("Getdoctor", "Visit")',
                dataType: 'json',
                data: (params) => {
                    return {
                        doctorname: params.term,
                    }
                },
                processResults: function (data, params) {
                    return {
                        results: data,
                    };
                    return {
                        results: results,
                    }
                },
            },
        });


        var patientname = $("#patientName").val();
        var datapatient = $("<option/>", { value: @Model.patientId, text: patientname });
        $('#patientId').append(datapatient);
        $('#patientId option[value="' + @Model.patientId, + '"]').prop('selected', true);
        $('#patientId').trigger('change');

        $("#patientId").select2({
            dropdownParent: $('#form-modalsss'),
            ajax: {
                url: '@Url.Action("GetPatient", "Visit")',
                dataType: 'json',
                data: (params) => {
                    return {
                        Patientname: params.term,
                    }
                },
                processResults: function (data, params) {
                    return {
                        results: data,
                    };
                    return {
                        results: results,
                    }
                },
            },
        });
        var clinictname = $("#ClinicName").val();
        var dataclinic = $("<option/>", { value: @Model.clinicID, text: clinictname });
        $('#clinicID').append(dataclinic);
        $('#clinicID option[value="' + @Model.clinicID, + '"]').prop('selected', true);
        $('#clinicID').trigger('change');

        $("#clinicID").select2({
            dropdownParent: $('#form-modalsss'),
            ajax: {
                url: '@Url.Action("GetClinic", "Visit")',
                dataType: 'json',
                data: (params) => {
                    return {
                        Clinictname: params.term,
                    }
                },
                processResults: function (data, params) {
                    return {
                        results: data,
                    };
                    return {
                        results: results,
                    }
                },
            },

        });
        
    })


</script>

Clinic Managment/Areas/Managment/Views/Visit/EditVisits.cshtml
@model  Clinic_Managment.VisitEditor
@{
    Layout = null;
}
<input type="text" id="doctorName" value="@Model.doctorName" style="display:none;" />
<input type="text" id="patientName" value="@Model.patientName" style="display:none;" />
<input type="text" id="ClinicName" value="@Model.ClinicName" style="display:none;" />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        <div class="form-group">
            <label class="col-md-3">
                Doctor
            </label>
            <div class="col-md-9">
                <span id="msgdoctor1" class="text-danger" style="display:none">Please, the Doctor value is not filled</span>
                <select id="doctorId" style="width:350px;">
                    @Html.ValidationMessageFor(x => x.doctorId, Model.doctorName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.doctorName, "", new { @class = "text-danger" })
                </select>

            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3">
                Patient
            </label>
            <div class="col-md-9">
                <span id="msgpatient1" class="text-danger" style="display:none">Please, the Patient value is not filled</span>
                <select id="patientId" style="width:350px;">
                    @Html.ValidationMessageFor(x => x.patientId, Model.patientName, new { @class = "form-control" })
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3">
                Clinic
            </label>
            <div class="col-md-9">
                <span id="msgClinic1" class="text-danger" style="display:none">Please, the Clinic value is not filled</span>
                <select id="clinicID" style="width:350px;">
                    @Html.ValidationMessageFor(x => x.clinicID, Model.ClinicName, new { @class = "form-control" })
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-3">
                VistDate
            </label>
            <div class="col-md-9">
                <span id="msgVistDate2" class="text-danger" style="display:none">The date is not real, please be greater than the date</span>
                <span id="msgVistDate1" class="text-danger" style="display:none">Please, the VistDate value is not filled</span>
                <span id="msgVistDate" class="text-danger" style="display:none">Please, the Date is in the database, choose another Date</span>
                <input class="form-control" asp-for="VistDate" asp-format="{0:yyyy-MM-ddTHH:mm}" />
            </div>
        </div>

        <br /><br /><br />
        <center>
            <div class="form-group">
                <div class="col-md-12">
                    <button type="button" onclick="SaveVisits()" class="btn btn-outline-primary" id="add_variation">Save</button>
                </div>
            </div>
        </center>
    </div>
}

<script type="text/javascript">
    debugger;
    var doctorname = $("#doctorName").val();
    var datadoctor = $("<option/>", { value: @Model.doctorId, text: doctorname });
    $('#doctorId').append(datadoctor);
    $('#doctorId option[value="' + @Model.doctorId, + '"]').prop('selected', true);
    $('#doctorId').trigger('change');

    $(document).ready(function () {
        $("#doctorId").select2({
            
            dropdownParent: $('#form-modal'),
            ajax: {
            url: '@Url.Action("Getdoctor", "Visit")',
                dataType: 'json',
                data: (params) => {
                    return {
                        doctorname: params.term,
                    }
                },
                processResults: function (data, params) {
                    return {
                        results: data,
                    };
                    return {
                        results: results,
                    }
                },
            },
        });


        var patientname = $("#patientName").val();
        var datapatient = $("<option/>", { value: @Model.patientId, text: patientname });
        $('#patientId').append(datapatient);
        $('#patientId option[value="' + @Model.patientId, + '"]').prop('selected', true);
        $('#patientId').trigger('change');

        $("#patientId").select2({
            dropdownParent: $('#form-modal'),
            ajax: {
                url: '@Url.Action("GetPatient", "Visit")',
                dataType: 'json',
                data: (params) => {
                    return {
                        Patientname: params.term,
                    }
                },
                processResults: function (data, params) {
                    return {
                        results: data,
                    };
                    return {
                        results: results,
                    }
                },
            },
        });
        var clinictname = $("#ClinicName").val();
        var dataclinic = $("<option/>", { value: @Model.clinicID, text: clinictname });
        $('#clinicID').append(dataclinic);
        $('#clinicID option[value="' + @Model.clinicID, + '"]').prop('selected', true);
        $('#clinicID').trigger('change');

        $("#clinicID").select2({
            dropdownParent: $('#form-modal'),
            ajax: {
                url: '@Url.Action("GetClinic", "Visit")',
                dataType: 'json',
                data: (params) => {
                    return {
                        Clinictname: params.term,
                    }
                },
                processResults: function (data, params) {
                    return {
                        results: data,
                    };
                    return {
                        results: results,
                    }
                },
            },
        });
    })
 

</script>

Clinic Managment/Areas/Managment/Views/Visit/GetDetailsVisits.cshtml
@model Clinic_Managment.Models.VisitsModels

@{
    Layout = null;
}

<div class="container">
    <div class="row">
        <label class="col-xs-2" for="lname">ID : </label>
        <label class="col-xs-10" for="lname">@Model.ID</label>
    </div>
    <br /><br />
    <div class="row">
        <label class="col-xs-2" for="fname">Doctor : </label>
        @if (Model.DoctorName != null)
        {
            <label class="col-xs-10" for="fname">@Model.DoctorName</label>
        }
        else
        {
            <span>
                N/a
            </span>
        }
       
    </div>


    <br /><br />
    <div class="row">
        <label class="col-xs-2" for="lname">Patient : </label>
        @if (Model.PatientName != null)
        {
            <label class="col-xs-10" for="lname">@Model.PatientName</label>
        }
        else
        {
            <span>
                N/a
            </span>
        }
    </div>
   

    <br /><br />
    <div class="row">
        <label class="col-xs-2" for="lname">Clinic : </label>
        @if (Model.Clinic != null)
        {
            <label class="col-xs-10" for="lname">@Model.Clinic</label>
        }
        else
        {
            <span>
                N/a
            </span>
        }
    </div>
    
    <br /><br />
    <div class="row">
        <label class="col-xs-2" for="lname">VistDate : </label>
        <label class="col-xs-10" for="lname">@Model.VistDate</label>
    </div>
</div>

Clinic Managment/Areas/Managment/Views/Visit/VisitItem.cshtml
@model Clinic_Managment.Models.VisitsModels
<tr id="Vists_@Model.ID">
    <td>@Model.ID </td>
    <td>
        @if (Model.DoctorName!= null)
        {
            @Model.DoctorName
        }
        else
        {
            <span>
                N/a
            </span>
        }

        </td>
    <td>
        @if (Model.PatientName != null)
        {
            @Model.PatientName
        }
        else
        {
            <span>
                N/a
            </span>
        }

    </td>
    <td>
        @if (Model.Clinic != null)
        {
            @Model.Clinic
        }
        else
        {
            <span>
                N/a
            </span>
        }

    </td>
    <td>@Model.VistDate</td>

    <td>
        <button type="button" onclick="Delete(@Model.ID)" class="btn btn-danger pull-right"><i class='fa fa-trash' style='font-size:18px'></i></button>
        <button type="button" onclick="GetDetails(@Model.ID)" class="btn btn-warning pull-right"><i class="fa fa-align-justify custom" style="font-size:18px"></i></button>
        <button type="button" onclick="Edit(@Model.ID)" class="btn btn-success pull-right"><i class="fa fa-edit" style="font-size:18px"></i></button>

</tr>

Clinic Managment/Areas/Managment/Views/Visit/visitlist.cshtml
@model IList<Clinic_Managment.Models.VisitsModels>

@foreach (var item in Model)
{
    @Html.Partial("VisitItem", item)
}