Clinic Managment/Areas/Managment/Controllers/StudentController.cs
using Clinic_Managment.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Plugins;
using MediatR;
using Microsoft.AspNetCore.Authentication;
using static Clinic_Managment.Areas.Managment.Query.StudentQuery;

namespace Clinic_Managment.Areas.Managment.Controllers
{
    [Area("Managment")]
    [Authorize]
  
    public class StudentController : Controller
    {
        private readonly MediatR.ISender _mediator;
        private readonly Userdata _context;
        public StudentController(MediatR.ISender mediator, Userdata userdata )
        {
            _mediator = mediator;
            _context = userdata;
        }
        public IActionResult StudentIndex()
        {
            List<StudentModel> Studentlist = new List<StudentModel>();
            var student = _context.studentModels;
            Studentlist = (from StudentModel in student
                          select StudentModel).ToList();
            return View(Studentlist);
        }
        [HttpGet]
        public async Task<IActionResult> EditStudent(int studentid)
        {
            var student = await _mediator.Send(new EditStudentModel(studentid));
            return View(student);
        }
        [HttpPost]
        public async Task<IActionResult> EditStudent(StudentModel studentModel)
        {
            var studentmodel = await _mediator.Send(new SaveStudentModel(studentModel));
            return View("StudentItem", studentmodel);
        }
        public async Task<IActionResult> GetDetailsStudent(int studentid)
        {
            var detailstudent = await _mediator.Send(new EditStudentModel(studentid));
             return View("GetDetailsStudent", detailstudent);
        }
    }
}

Clinic Managment/Areas/Managment/Views/Student/EditStudent.cshtml
@model Clinic_Managment.Models.StudentModel

@{
    Layout = null;
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.StudentId)

        <div class="form-group">
            <span id="msgName1" class="text-danger" style="display:none">Please, the studentName is in the database, choose another studentName</span>
            <span id="msgdoctor94941" class="text-danger" style="display:none">Please, the studentName value is not filled</span>
            <br>
            <label class="col-md-3">
                Name
            </label>
            <div class="col-md-9">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <br /><br /><br />
        <center>
            <div class="form-group">
                <div class="col-md-12">
                    <button type="button" onclick="SaveStudent()" class="btn btn-success-white">Save</button>
                </div>
            </div>
        </center>

    </div>


}

Clinic Managment/Areas/Managment/Views/Student/GetDetailsStudent.cshtml
@model Clinic_Managment.Models.StudentModel

@{
    Layout = null;
}

<div class="container">
    <div class="row">
        <label class="col-xs-2" for="lname">StudentId : </label>
        <label class="col-xs-10" for="lname">@Model.StudentId</label>
    </div>
    <br /><br />
    <div class="row">
        <label class="col-xs-2" for="fname">Name : </label>
        <label class="col-xs-10" for="fname">@Model.Name</label>
    </div>

</div>

Clinic Managment/Areas/Managment/Views/Student/SearchStudent.cshtml
@model IList<Clinic_Managment.Models.StudentModel>

@foreach (var item in Model)
{
    @Html.Partial("StudentItem", item)
}

Clinic Managment/Areas/Managment/Views/Student/StudentIndex.cshtml
@model IList<Clinic_Managment.Models.StudentModel>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/js/select2.min.js" defer></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <select id="mySelect2" multiple="multiple" style="width:300px;">
    </select>
    <button type="button" onclick="Search()" class="btn btn-info"><i class="fa fa-search"></i></button>
</div>

<div class="row">
    <div class="col-xs-12">
        <table class="table table-hover table" id="tables">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th>
                        <button type="button" onclick="Edit()" class="btn btn-info"><i class="fa fa-plus  style='font-size:18px'" aria-hidden="true"></i></button>
                    </th>

                    <th></th>
                </tr>

            </thead>
            <tbody id="teachersBody">

                @Html.Partial("SearchStudent", Model)
            </tbody>
        </table>

    </div>
</div>



<div class="modal" tabindex="-1" id="form-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Add and Edit Student</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="form-modal-body">
            </div>

        </div>
    </div>
</div>

<div class="modal" tabindex="-1" id="form-modals">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Details Student</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="form-modal-bodys">
            </div>

        </div>
    </div>
</div>


<div class="modal" tabindex="-1" role="dialog" id="Mymodal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">

                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body" id="deletemodals">
                <h3>Do you want to delete, answer yes or no.</h3>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">No</button>
                <button type="button" class="btn btn-success" onclick="ConfirmDelete()">Yes</button>
            </div>
        </div>
    </div>
</div>


<script>
    function GetDetailsStuden(studentids) {
        $.ajax({
            type: "GET",
            url: "@Url.Action("GetDetailsStudent", "Student")",
            data: { studentid: studentids },
            success: function (data) {
                debugger;
                $('#form-modal-bodys').html('');
                $('#form-modal-bodys').html(data);
                $('#form-modals').modal('show');
            }
        })
    }

    function Edit(studentid) {
        $.ajax({
            type: "GET",
            url: "@Url.Action("EditStudent", "Student")",
            data: { studentid: studentid },
            success: function (data) {
                debugger;
                $('#form-modal-body').html('');
                $('#form-modal-body').html(data);
                $('#form-modal').modal('show');
            }
        })
    }
    debugger;
    function SaveStudent() {
        debugger;
        var obj = new Object();
        obj.StudentId = $("#StudentId").val();
        obj.Name = $("#Name").val();

        var name = $("#Name").val();
        var isvalid = true;
        if (name == "") {
            $("#msgName1").hide();
            $("#msgdoctor94941").show();
            isvalid = false;
        }
        else {
            $("#msgdoctor94941").hide();
        }
        debugger;
        $.ajax({
            type: "POST",
            url: '@Url.Action("EditStudent", "Student")',
            data: { studentModel: obj },

            success: function (data) {
                debugger;
                    $("#msgName1").hide();
                    $("#form-modal").modal('hide');
                    if ($('#StudentId').val() && $('#StudentId').val() > 0) {
                     $('#Student_' + $('#StudentId').val()).replaceWith(data);
                    }
                    else {
                      $('#teachersBody').append(data);
                    }
            }

        });
    }

</script>

Clinic Managment/Areas/Managment/Views/Student/StudentItem.cshtml
@model Clinic_Managment.Models.StudentModel

<tr id="Student_@Model.StudentId">
    <td>@Model.StudentId </td>
    <td>@Model.Name </td>

    <td>
        <button type="button" onclick="Delete(@Model.StudentId)" class="btn btn-danger pull-right"><i class='fa fa-trash' style='font-size:18px'></i></button>
        <button type="button" onclick="GetDetailsStuden(@Model.StudentId)" class="btn btn-warning pull-right"><i class="fa fa-align-justify custom" style="font-size:18px"></i></button>
        <button type="button" onclick="Edit(@Model.StudentId)" class="btn btn-success pull-right"><i class="fa fa-edit" style="font-size:18px"></i></button>

</tr>