Clinic Managment/Models/Doctor.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using NuGet.DependencyResolver;

namespace Clinic_Managment.Models
{
    public class Doctor
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public int doctorId { get; set; }
        public string Name { get; set; }
        public virtual ICollection<Visit> Visits { get; set; }

    }
}

Clinic Managment/Areas/Managment/Controllers/DoctorController.cs
using ChartJSCore.Plugins.Zoom;
using Clinic_Managment.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuGet.DependencyResolver;
using NuGet.Protocol.Plugins;
using System.Numerics;

namespace Clinic_Managment.Areas.Managment.Controllers
{
    [Area("Managment")]
    [Authorize]
    public class DoctorController : Controller
    {
        private readonly Userdata _context;
        public DoctorController(Userdata context)
        {
            _context = context;
        }
        public IActionResult DoctorIndex()
        {
            List<Doctor> Doctorlist = new List<Doctor>();
           var doctor = _context.Doctor;
            Doctorlist = (from Doctors in doctor
                           select Doctors).ToList();
            return View(Doctorlist);

        }
        public JsonResult GetDoctors(string searchdoctor , string selectdoctorid)
        {
                List<Doctor> Doctors = new List<Doctor>();
            if (!string.IsNullOrEmpty(selectdoctorid)){
                var ids = selectdoctorid.Split(',').Select(Int32.Parse).ToList();
                Doctors = _context.Doctor.Where(x => !ids.Contains(x.doctorId)).ToList();
            }
            else
            {
                Doctors = _context.Doctor.Where(x => x.Name.Contains(searchdoctor)).ToList();
            }
            var modifieData = Doctors.Select(x => new
            {
                id = x.doctorId,
                text = x.Name
            });
            return Json(modifieData);
        }


        public IActionResult SearchDoctor(string idsStr)
        {
            List<Doctor> SearchList = new List<Doctor>();

            if (!string.IsNullOrEmpty(idsStr))
            {
                var ids = idsStr.Split(',').Select(Int32.Parse).ToList();
                SearchList = (from n in _context.Doctor
                              where ids.Contains(n.doctorId)
                              select n).ToList();
            }
            else
            {
                SearchList = (from n in _context.Doctor

                              select n).ToList();
            }

            return PartialView("SearchDoctor", SearchList);
        }

        [HttpPost]
        public IActionResult DeleteDoctor(int teacherID)
        {
            try
            {


                Doctor com = _context.Doctor.Where(x => x.doctorId == teacherID).FirstOrDefault();
                _context.Doctor.Remove(com);
                _context.SaveChanges();


                return Ok(new { success = true });
            }

            catch (Exception)
            {
                return Json(new { success = false });
            }
        }
        public IActionResult GetDetailsDoctor(int? id)
        {

            Doctor obj = new Doctor();

            obj = (from y in _context.Doctor
                   where y.doctorId == id
                   select y).FirstOrDefault();
            return View("GetDetailsDoctor", obj);

        }
        public IActionResult EditDoctor(int? id)
        {

            return View(_context.Doctor.Find(id));
        }

        [HttpPost]
        public IActionResult EditDoctor(Doctor doctor)
        {
            if (_context.Doctor.Any(a => a.Name.Equals(doctor.Name)))
            {
                return Ok("doctornames");
            }
            else
            {
                if (doctor.doctorId == 0)
                {
                    _context.Entry(doctor).State = EntityState.Added;
                    _context.SaveChanges();
                }
                else
                {
                    _context.Entry(doctor).State = EntityState.Modified;
                    _context.SaveChanges();
                }
                return PartialView("DoctorItem", doctor);
            }
        }
    }
}

Clinic Managment/Areas/Managment/Views/Doctor/DoctorIndex.cshtml
@model IList<Clinic_Managment.Models.Doctor>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/js/select2.min.js" defer></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <select id="mySelect2" multiple="multiple" style="width:300px;">
    </select>
    <button type="button" onclick="Search()" class="btn btn-info"><i class="fa fa-search"></i></button>
</div>

<div class="row">
    <div class="col-xs-12">
        <table class="table table-hover table" id="tables">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th>
                        <button type="button" onclick="Edit()" class="btn btn-info"><i class="fa fa-plus  style='font-size:18px'" aria-hidden="true"></i></button>
                    </th>

                    <th></th>
                </tr>

            </thead>

            <tbody id="teachersBody">
                @Html.Partial("SearchDoctor", Model)
            </tbody>
        </table>

    </div>
</div>



<div class="modal" tabindex="-1" id="form-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Add and Edit Doctor</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="form-modal-body">
            </div>

        </div>
    </div>
</div>

<div class="modal" tabindex="-1" id="form-modals">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Details Doctor</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="form-modal-bodys">
            </div>

        </div>
    </div>
</div>


<div class="modal" tabindex="-1" role="dialog" id="Mymodal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">

                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body" id="deletemodals">
                <h3>Do you want to delete, answer yes or no.</h3>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">No</button>
                <button type="button" class="btn btn-success" onclick="ConfirmDelete()">Yes</button>
            </div>
        </div>
    </div>
</div>


<script>
    $(document).ready(function () {
        debugger;
    $("#mySelect2").select2({
        allowClear: true,
        theme: "classic",
        minimumInputLength: 1,
        ajax: {
            url: '@Url.Action("GetDoctors", "Doctor")',
            dataType: "json",

             data: function (params) {
                return {
                  searchdoctor: params.term,
                  selectdoctorid: $("#mySelect2").val().toString(),
                }

               
            },
            processResults: function (data, params) {
                return {
                    results: data,
                };
            },
        },
     })
    })
    function Search() {

        var ids = $("#mySelect2").val();
        $.ajax
            ({
                type: "GET",
                url: '@Url.Action("SearchDoctor", "Doctor")',
                data: { idsStr: ids.toString() },
                success: function (data) {
                    debugger;
                    $('#teachersBody').html(data);
                }
            });
    }

    function ConfirmDelete() {
        $.ajax({
            type: "POST",
            url: '@Url.Action("DeleteDoctor", "Doctor")',
            data: { teacherID: Cid },
            success: function (data) {

                $("#Mymodal").modal('hide');
                $('#Doctor_' + Cid).remove();

            }

        })
    }

    function Delete(CoId) {
        Cid = CoId;

        $("#Mymodal").modal('show');
    }


    function GetDetails(teacherID) {
        $.ajax({
            type: "GET",
            url: "@Url.Action("GetDetailsDoctor", "Doctor")",
            data: { id: teacherID },
            success: function (data) {
                debugger;
                $('#form-modal-bodys').html('');
                $('#form-modal-bodys').html(data);
                $('#form-modals').modal('show');
            }
        })
    }

    function Edit(teacherID) {
        $.ajax({
            type: "GET",
            url: "@Url.Action("EditDoctor", "Doctor")",
            data: { id: teacherID },
            success: function (data) {
                debugger;
                $('#form-modal-body').html('');
                $('#form-modal-body').html(data);
                $('#form-modal').modal('show');
            }
        })
    }
    debugger;
    function Savedoctor() {
        debugger;
        var obj = new Object();
        obj.doctorId = $("#doctorId").val();
        obj.Name = $("#Name").val();

        var name = $("#Name").val();
        var isvalid = true;
        if(name == ""){
            $("#msgName1").hide();
            $("#msgdoctor94941").show();
            isvalid = false;
        }
        else{
            $("#msgdoctor94941").hide();
        }
        debugger;
        $.ajax({
            type: "POST",
            url: '@Url.Action("EditDoctor", "Doctor")',
            data: { doctor: obj },

            success: function (data) {
                debugger;
                if (data == "doctornames"){
                    $("#msgName1").show();
                }
                else{
                    $("#msgName1").hide();
                    $("#form-modal").modal('hide');
                    if ($('#doctorId').val() && $('#doctorId').val() > 0) {
                        $('#Doctor_' + $('#doctorId').val()).replaceWith(data);
                    }
                    else {
                        $('tbody').append(data);
                    }
                }
                

            }

        });
    }

</script>

Clinic Managment/Areas/Managment/Views/Doctor/DoctorItem.cshtml
@model Clinic_Managment.Models.Doctor

<tr id="Doctor_@Model.doctorId">
    <td>@Model.doctorId </td>
    <td>@Model.Name </td>

    <td>
        <button type="button" onclick="Delete(@Model.doctorId)" class="btn btn-danger pull-right"><i class='fa fa-trash' style='font-size:18px'></i></button>
        <button type="button" onclick="GetDetails(@Model.doctorId)" class="btn btn-warning pull-right"><i class="fa fa-align-justify custom" style="font-size:18px"></i></button>
        <button type="button" onclick="Edit(@Model.doctorId)" class="btn btn-success pull-right"><i class="fa fa-edit" style="font-size:18px"></i></button>

</tr>

Clinic Managment/Areas/Managment/Views/Doctor/EditDoctor.cshtml
@model Clinic_Managment.Models.Doctor

@{
    Layout = null;
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.doctorId)

        <div class="form-group">
            <span id="msgName1" class="text-danger" style="display:none">Please, the doctorname is in the database, choose another doctorname</span>
            <span id="msgdoctor94941" class="text-danger" style="display:none">Please, the doctorname value is not filled</span>
            <br>
            <label class="col-md-3">
                Name
            </label>
            <div class="col-md-9">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <br /><br /><br />
        <center>
            <div class="form-group">
                <div class="col-md-12">
                    <button type="button" onclick="Savedoctor()" class="btn btn-success-white">Save</button>
                </div>
            </div>
        </center>

    </div>


}

Clinic Managment/Areas/Managment/Views/Doctor/GetDetailsDoctor.cshtml
@model Clinic_Managment.Models.Doctor

@{
    Layout = null;
}

<div class="container">
    <div class="row">
        <label class="col-xs-2" for="lname">DoctorID : </label>
        <label class="col-xs-10" for="lname">@Model.doctorId</label>
    </div>
    <br /><br />
    <div class="row">
        <label class="col-xs-2" for="fname">Name : </label>
        <label class="col-xs-10" for="fname">@Model.Name</label>
    </div>

</div>

Clinic Managment/Areas/Managment/Views/Doctor/SearchDoctor.cshtml
@model IList<Clinic_Managment.Models.Doctor>

@foreach (var item in Model)
{
    @Html.Partial("DoctorItem", item)
}